// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/messages.proto

package order

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the user who made the order.
	// Must be a valid uuid.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Vegetables that are selected to be ordered.
	// Min number of items - 1.
	OrderItems    []*OrderItemInput `protobuf:"bytes,2,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderItems() []*OrderItemInput {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type OrderItemInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the vegetable.
	// Must be a valid uuid.
	VegetableId string `protobuf:"bytes,1,opt,name=vegetable_id,json=vegetableId,proto3" json:"vegetable_id,omitempty"`
	// Weight of the vegetable
	// Must be greater that 0.0 kg
	Weight float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Recipient information.
	// There provided detailed information about recipient.
	RecipientInfo *RecipientInfo `protobuf:"bytes,3,opt,name=recipient_info,json=recipientInfo,proto3" json:"recipient_info,omitempty"`
	// Address.
	// The address where this part of order will be delivered.
	AddressInfo   *AddressInfo `protobuf:"bytes,4,opt,name=address_info,json=addressInfo,proto3" json:"address_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_order_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemInput) GetVegetableId() string {
	if x != nil {
		return x.VegetableId
	}
	return ""
}

func (x *OrderItemInput) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *OrderItemInput) GetRecipientInfo() *RecipientInfo {
	if x != nil {
		return x.RecipientInfo
	}
	return nil
}

func (x *OrderItemInput) GetAddressInfo() *AddressInfo {
	if x != nil {
		return x.AddressInfo
	}
	return nil
}

type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the order item.
	OrderItemId string `protobuf:"bytes,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	// Identifier of the vegetable.
	// Must be a valid uuid.
	VegetableId string `protobuf:"bytes,2,opt,name=vegetable_id,json=vegetableId,proto3" json:"vegetable_id,omitempty"`
	// Weight of the vegetable
	// Must be greater that 0.0 kg
	Weight float32 `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Vegetable price per kg without discount.
	Price float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	// Discounted price of the vegetable per kg.
	// While there is no discount, it is equal to the price.
	DiscountedPrice float32 `protobuf:"fixed32,5,opt,name=discounted_price,json=discountedPrice,proto3" json:"discounted_price,omitempty"`
	// Recipient information.
	// There provided detailed information about recipient.
	RecipientInfo *RecipientInfo `protobuf:"bytes,6,opt,name=recipient_info,json=recipientInfo,proto3" json:"recipient_info,omitempty"`
	// Address.
	// The address where this part of order will be delivered.
	AddressInfo   *AddressInfo `protobuf:"bytes,7,opt,name=address_info,json=addressInfo,proto3" json:"address_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItem) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *OrderItem) GetVegetableId() string {
	if x != nil {
		return x.VegetableId
	}
	return ""
}

func (x *OrderItem) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *OrderItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetDiscountedPrice() float32 {
	if x != nil {
		return x.DiscountedPrice
	}
	return 0
}

func (x *OrderItem) GetRecipientInfo() *RecipientInfo {
	if x != nil {
		return x.RecipientInfo
	}
	return nil
}

func (x *OrderItem) GetAddressInfo() *AddressInfo {
	if x != nil {
		return x.AddressInfo
	}
	return nil
}

type CreateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the order that was just created.
	OrderId       string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the order.
	// Must be a valid uuid.
	OrderId       string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order.
	// Contains detailed information about the order,
	// the recipient and the vegetables that were ordered
	Order         *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the order.
	// Must be a valid uuid.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the user who made the order.
	// Must be a valid uuid.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Total amount.
	TotalAmount float32 `protobuf:"fixed32,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Order items.
	OrderItems    []*OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type RecipientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First name of the order recipient.
	// Must be at least 2 characters long.
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name of the order recipient.
	// Must be at least 2 characters long.
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Phone number of the recipient.
	// Must be 9 numbers long.
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Email of the recipient.
	// Must be a valid email address.
	Email         string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientInfo) Reset() {
	*x = RecipientInfo{}
	mi := &file_order_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientInfo) ProtoMessage() {}

func (x *RecipientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientInfo.ProtoReflect.Descriptor instead.
func (*RecipientInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RecipientInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RecipientInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RecipientInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RecipientInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddressInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address.
	// The address where the order will be delivered.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_order_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the user who made orders
	// Must be a valid uuid.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The maximum number of orders to return. The service may return fewer than
	// this value.
	// If unspecified or equals to 0, at most 50 orders will be returned.
	// The maximum value is 1000.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset (0-based)
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Filter by specific order IDs
	// Example: ["14afdc88-596e-413d-98cc-d637b0c69c80", "e2c0a7d8-4a2f-4e8d-bd6a-8f8b8d7d8e9f"]
	OrderIds      []string `protobuf:"bytes,4,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOrdersRequest) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ListOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of orders.
	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	// The total size of the list of orders.
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_order_v1_messages_proto protoreflect.FileDescriptor

const file_order_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17order/v1/messages.proto\x12\border.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x82\x01\n" +
	"\x12CreateOrderRequest\x12$\n" +
	"\auser_id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12F\n" +
	"\vorder_items\x18\x02 \x03(\v2\x18.order.v1.OrderItemInputB\v\xe0A\x02\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"orderItems\"\xf7\x01\n" +
	"\x0eOrderItemInput\x12.\n" +
	"\fvegetable_id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\vvegetableId\x12%\n" +
	"\x06weight\x18\x02 \x01(\x02B\r\xe0A\x02\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12I\n" +
	"\x0erecipient_info\x18\x03 \x01(\v2\x17.order.v1.RecipientInfoB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\rrecipientInfo\x12C\n" +
	"\faddress_info\x18\x04 \x01(\v2\x15.order.v1.AddressInfoB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\vaddressInfo\"\xfa\x02\n" +
	"\tOrderItem\x12'\n" +
	"\rorder_item_id\x18\x01 \x01(\tB\x03\xe0A\bR\vorderItemId\x12.\n" +
	"\fvegetable_id\x18\x02 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\vvegetableId\x12%\n" +
	"\x06weight\x18\x03 \x01(\x02B\r\xe0A\x02\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12#\n" +
	"\x05price\x18\x04 \x01(\x02B\r\xe0A\x02\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x05price\x128\n" +
	"\x10discounted_price\x18\x05 \x01(\x02B\r\xe0A\x02\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\x0fdiscountedPrice\x12I\n" +
	"\x0erecipient_info\x18\x06 \x01(\v2\x17.order.v1.RecipientInfoB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\rrecipientInfo\x12C\n" +
	"\faddress_info\x18\a \x01(\v2\x15.order.v1.AddressInfoB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\vaddressInfo\"0\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"9\n" +
	"\x0fGetOrderRequest\x12&\n" +
	"\border_id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\aorderId\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"\xac\x01\n" +
	"\x05Order\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12-\n" +
	"\ftotal_amount\x18\x03 \x01(\x02B\n" +
	"\xbaH\a\n" +
	"\x05%\x00\x00\x00\x00R\vtotalAmount\x124\n" +
	"\vorder_items\x18\x04 \x03(\v2\x13.order.v1.OrderItemR\n" +
	"orderItems\"\xa9\x01\n" +
	"\rRecipientInfo\x12&\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x02R\tfirstName\x12$\n" +
	"\tlast_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x02R\blastName\x12+\n" +
	"\fphone_number\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01\tR\vphoneNumber\x12\x1d\n" +
	"\x05email\x18\x04 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\"0\n" +
	"\vAddressInfo\x12!\n" +
	"\aaddress\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x05R\aaddress\"\x9d\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\x05limit\x18\x02 \x01(\x03B\n" +
	"\xbaH\a\"\x05\x18\xe8\a(\x00R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x06offset\x12,\n" +
	"\torder_ids\x18\x04 \x03(\tB\x0f\xbaH\f\x92\x01\t\x18\x01\"\x05r\x03\xb0\x01\x01R\borderIds\"\\\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSizeB\xa3\x01\n" +
	"\fcom.order.v1B\rMessagesProtoP\x01ZCgitbub.com/escoutdoor/vegetable_store/common/pkg/api/order/v1;order\xa2\x02\x03OXX\xaa\x02\bOrder.V1\xca\x02\bOrder\\V1\xe2\x02\x14Order\\V1\\GPBMetadata\xea\x02\tOrder::V1b\x06proto3"

var (
	file_order_v1_messages_proto_rawDescOnce sync.Once
	file_order_v1_messages_proto_rawDescData []byte
)

func file_order_v1_messages_proto_rawDescGZIP() []byte {
	file_order_v1_messages_proto_rawDescOnce.Do(func() {
		file_order_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_messages_proto_rawDesc), len(file_order_v1_messages_proto_rawDesc)))
	})
	return file_order_v1_messages_proto_rawDescData
}

var file_order_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_v1_messages_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),  // 0: order.v1.CreateOrderRequest
	(*OrderItemInput)(nil),      // 1: order.v1.OrderItemInput
	(*OrderItem)(nil),           // 2: order.v1.OrderItem
	(*CreateOrderResponse)(nil), // 3: order.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),     // 4: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),    // 5: order.v1.GetOrderResponse
	(*Order)(nil),               // 6: order.v1.Order
	(*RecipientInfo)(nil),       // 7: order.v1.RecipientInfo
	(*AddressInfo)(nil),         // 8: order.v1.AddressInfo
	(*ListOrdersRequest)(nil),   // 9: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),  // 10: order.v1.ListOrdersResponse
}
var file_order_v1_messages_proto_depIdxs = []int32{
	1, // 0: order.v1.CreateOrderRequest.order_items:type_name -> order.v1.OrderItemInput
	7, // 1: order.v1.OrderItemInput.recipient_info:type_name -> order.v1.RecipientInfo
	8, // 2: order.v1.OrderItemInput.address_info:type_name -> order.v1.AddressInfo
	7, // 3: order.v1.OrderItem.recipient_info:type_name -> order.v1.RecipientInfo
	8, // 4: order.v1.OrderItem.address_info:type_name -> order.v1.AddressInfo
	6, // 5: order.v1.GetOrderResponse.order:type_name -> order.v1.Order
	2, // 6: order.v1.Order.order_items:type_name -> order.v1.OrderItem
	6, // 7: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_order_v1_messages_proto_init() }
func file_order_v1_messages_proto_init() {
	if File_order_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_messages_proto_rawDesc), len(file_order_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_v1_messages_proto_goTypes,
		DependencyIndexes: file_order_v1_messages_proto_depIdxs,
		MessageInfos:      file_order_v1_messages_proto_msgTypes,
	}.Build()
	File_order_v1_messages_proto = out.File
	file_order_v1_messages_proto_goTypes = nil
	file_order_v1_messages_proto_depIdxs = nil
}
