// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/service.proto

package order

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_v1_service_proto protoreflect.FileDescriptor

const file_order_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16order/v1/service.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17order/v1/messages.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xb0\x02\n" +
	"\fOrderService\x12a\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12`\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12[\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/ordersB\xf1\x01\x92AL\x12F\n" +
	"\x1dVegetable Store Order Service\" \n" +
	"\n" +
	"Ivan Popov\x1a\x12vanap387@gmail.com2\x031.0*\x02\x01\x02\n" +
	"\fcom.order.v1B\fServiceProtoP\x01ZCgitbub.com/escoutdoor/vegetable_store/common/pkg/api/order/v1;order\xa2\x02\x03OXX\xaa\x02\bOrder.V1\xca\x02\bOrder\\V1\xe2\x02\x14Order\\V1\\GPBMetadata\xea\x02\tOrder::V1b\x06proto3"

var file_order_v1_service_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),  // 0: order.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),     // 1: order.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),   // 2: order.v1.ListOrdersRequest
	(*CreateOrderResponse)(nil), // 3: order.v1.CreateOrderResponse
	(*GetOrderResponse)(nil),    // 4: order.v1.GetOrderResponse
	(*ListOrdersResponse)(nil),  // 5: order.v1.ListOrdersResponse
}
var file_order_v1_service_proto_depIdxs = []int32{
	0, // 0: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	1, // 1: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	2, // 2: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	3, // 3: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	4, // 4: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	5, // 5: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_v1_service_proto_init() }
func file_order_v1_service_proto_init() {
	if File_order_v1_service_proto != nil {
		return
	}
	file_order_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_service_proto_rawDesc), len(file_order_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_service_proto_goTypes,
		DependencyIndexes: file_order_v1_service_proto_depIdxs,
	}.Build()
	File_order_v1_service_proto = out.File
	file_order_v1_service_proto_goTypes = nil
	file_order_v1_service_proto_depIdxs = nil
}
