services:
  vegetable-service:
    container_name: vegetable-service
    restart: unless-stopped
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    volumes:
      - ../swagger:/app/swagger
      # - ./:/app
    ports:
      - 8080:8080 # grpc
      - 2040:2040 # gateway
      - 9020:9020 # swagger
      - 4040:4040 # prometheus server

  pg:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vegetables
      - POSTGRES_USER=escoutdoor
      - POSTGRES_PASSWORD=escoutdoor
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
