services:
  pg:
    image: postgres:17.5
    ports:
      - 5452:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=escoutdoor
      - POSTGRES_PASSWORD=escoutdoor
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
