// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vegetable/v1/service.proto

package vegetable

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_vegetable_v1_service_proto protoreflect.FileDescriptor

const file_vegetable_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1avegetable/v1/service.proto\x12\fvegetable.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bvegetable/v1/messages.proto2\xb9\x06\n" +
	"\x10VegetableService\x12y\n" +
	"\x0fCreateVegetable\x12$.vegetable.v1.CreateVegetableRequest\x1a%.vegetable.v1.CreateVegetableResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/vegetables\x12\x85\x01\n" +
	"\x0fDeleteVegetable\x12$.vegetable.v1.DeleteVegetableRequest\x1a%.vegetable.v1.DeleteVegetableResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/vegetables/{vegetable_id}\x12|\n" +
	"\fGetVegetable\x12!.vegetable.v1.GetVegetableRequest\x1a\".vegetable.v1.GetVegetableResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/vegetables/{vegetable_id}\x12s\n" +
	"\x0eListVegetables\x12#.vegetable.v1.ListVegetablesRequest\x1a$.vegetable.v1.ListVegetablesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/vegetables\x12\x94\x01\n" +
	"\x0fUpdateVegetable\x12$.vegetable.v1.UpdateVegetableRequest\x1a%.vegetable.v1.UpdateVegetableResponse\"4\x82\xd3\xe4\x93\x02.:\x06update2$/v1/vegetables/{update.vegetable_id}\x12\x97\x01\n" +
	"\x15BatchUpdateVegetables\x12*.vegetable.v1.BatchUpdateVegetablesRequest\x1a+.vegetable.v1.BatchUpdateVegetablesResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/vegetables:batchUpdateB\x91\x02\x92AP\x12J\n" +
	"!Vegetable Store Vegetable Service\" \n" +
	"\n" +
	"Ivan Popov\x1a\x12vanap387@gmail.com2\x031.0*\x02\x01\x02\n" +
	"\x10com.vegetable.v1B\fServiceProtoP\x01ZKgitbub.com/escoutdoor/vegetable_store/common/pkg/api/vegetable/v1;vegetable\xa2\x02\x03VXX\xaa\x02\fVegetable.V1\xca\x02\fVegetable\\V1\xe2\x02\x18Vegetable\\V1\\GPBMetadata\xea\x02\rVegetable::V1b\x06proto3"

var file_vegetable_v1_service_proto_goTypes = []any{
	(*CreateVegetableRequest)(nil),        // 0: vegetable.v1.CreateVegetableRequest
	(*DeleteVegetableRequest)(nil),        // 1: vegetable.v1.DeleteVegetableRequest
	(*GetVegetableRequest)(nil),           // 2: vegetable.v1.GetVegetableRequest
	(*ListVegetablesRequest)(nil),         // 3: vegetable.v1.ListVegetablesRequest
	(*UpdateVegetableRequest)(nil),        // 4: vegetable.v1.UpdateVegetableRequest
	(*BatchUpdateVegetablesRequest)(nil),  // 5: vegetable.v1.BatchUpdateVegetablesRequest
	(*CreateVegetableResponse)(nil),       // 6: vegetable.v1.CreateVegetableResponse
	(*DeleteVegetableResponse)(nil),       // 7: vegetable.v1.DeleteVegetableResponse
	(*GetVegetableResponse)(nil),          // 8: vegetable.v1.GetVegetableResponse
	(*ListVegetablesResponse)(nil),        // 9: vegetable.v1.ListVegetablesResponse
	(*UpdateVegetableResponse)(nil),       // 10: vegetable.v1.UpdateVegetableResponse
	(*BatchUpdateVegetablesResponse)(nil), // 11: vegetable.v1.BatchUpdateVegetablesResponse
}
var file_vegetable_v1_service_proto_depIdxs = []int32{
	0,  // 0: vegetable.v1.VegetableService.CreateVegetable:input_type -> vegetable.v1.CreateVegetableRequest
	1,  // 1: vegetable.v1.VegetableService.DeleteVegetable:input_type -> vegetable.v1.DeleteVegetableRequest
	2,  // 2: vegetable.v1.VegetableService.GetVegetable:input_type -> vegetable.v1.GetVegetableRequest
	3,  // 3: vegetable.v1.VegetableService.ListVegetables:input_type -> vegetable.v1.ListVegetablesRequest
	4,  // 4: vegetable.v1.VegetableService.UpdateVegetable:input_type -> vegetable.v1.UpdateVegetableRequest
	5,  // 5: vegetable.v1.VegetableService.BatchUpdateVegetables:input_type -> vegetable.v1.BatchUpdateVegetablesRequest
	6,  // 6: vegetable.v1.VegetableService.CreateVegetable:output_type -> vegetable.v1.CreateVegetableResponse
	7,  // 7: vegetable.v1.VegetableService.DeleteVegetable:output_type -> vegetable.v1.DeleteVegetableResponse
	8,  // 8: vegetable.v1.VegetableService.GetVegetable:output_type -> vegetable.v1.GetVegetableResponse
	9,  // 9: vegetable.v1.VegetableService.ListVegetables:output_type -> vegetable.v1.ListVegetablesResponse
	10, // 10: vegetable.v1.VegetableService.UpdateVegetable:output_type -> vegetable.v1.UpdateVegetableResponse
	11, // 11: vegetable.v1.VegetableService.BatchUpdateVegetables:output_type -> vegetable.v1.BatchUpdateVegetablesResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_vegetable_v1_service_proto_init() }
func file_vegetable_v1_service_proto_init() {
	if File_vegetable_v1_service_proto != nil {
		return
	}
	file_vegetable_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vegetable_v1_service_proto_rawDesc), len(file_vegetable_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vegetable_v1_service_proto_goTypes,
		DependencyIndexes: file_vegetable_v1_service_proto_depIdxs,
	}.Build()
	File_vegetable_v1_service_proto = out.File
	file_vegetable_v1_service_proto_goTypes = nil
	file_vegetable_v1_service_proto_depIdxs = nil
}
